# name: "Terraform-Destroy-Infra"

# on:
#   workflow_run:
#     workflows: ["Terraform-Apply-Infra-Release"]
#     types:
#       - completed

# jobs:
#   terraform_destroy:
#     name: "Terraform Destroy"
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v1
#         with:
#           cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

#       - name: Terraform Destroy
#         run: terraform destroy -auto-approve